services:
  vllm:
    image: vllm/vllm-openai:latest
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: ["--model", "mistralai/Mistral-7B-Instruct-v0.3"]
    environment:
      - HUGGING_FACE_HUB_TOKEN=HF_TOKEN
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    ports:
      - "8000:8000"
    ipc: host

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    environment:
      - OPENAI_API_BASE_URL=http://vllm:8000/v1
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    depends_on:
      - vllm
